import { Telegraf, Markup, type Context } from 'telegraf';
import { config, isAdmin } from './config.js';
import { db, many, one } from './db.js';
import { admin as adminKb, back, home } from './ui.js';

const bot = new Telegraf(config.BOT_TOKEN);
type Campaign = {id:number,title:string,description:string,media_file_id:string|null,media_type:string|null,access_type:'free'|'paid'|'invite',target:number|null,gofile_url:string,price_text:string|null,status:string,release_version:number};
type Ad = {id:number,name:string,body:string,media_file_id:string|null,media_type:string|null,enabled:boolean,last_sent_at:Date|null};
const esc=(s:string)=>s.replace(/[&<>]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[c]!));
async function ensureUser(ctx:Context){ if(!ctx.from)return; await db.query(`INSERT INTO users(telegram_id,username,first_name) VALUES($1,$2,$3) ON CONFLICT(telegram_id) DO UPDATE SET username=$2,first_name=$3,updated_at=now()`,[ctx.from.id,ctx.from.username??null,ctx.from.first_name]); }
async function showHome(ctx:Context,text='Bienvenue. Choisis une option :'){ await ensureUser(ctx); const x={parse_mode:'HTML' as const,...home(isAdmin(ctx.from?.id))}; try{await ctx.editMessageText(text,x)}catch{await ctx.reply(text,x)} }
async function privateOnly(ctx:Context){if(ctx.chat?.type!=='private'){await ctx.answerCbQuery?.('Ouvre le bot en privé.');return false}return true}
async function getOrCreateLink(userId:number){
 let row=await one<{invite_link:string}>(`SELECT invite_link FROM invite_links WHERE owner_id=$1 AND revoked_at IS NULL ORDER BY id DESC LIMIT 1`,[userId]);
 if(row)return row.invite_link;
 const link=await bot.telegram.createChatInviteLink(config.MAIN_GROUP_ID,{name:`ref_${userId}_${Date.now()}`,creates_join_request:false});
 await db.query(`INSERT INTO invite_links(owner_id,invite_link,telegram_link_name) VALUES($1,$2,$3)`,[userId,link.invite_link,link.name]); return link.invite_link;
}
async function publish(c:Campaign){
 const type=c.access_type==='free'?'GRATUIT':c.access_type==='paid'?'PAYANT':`INVITATION · ${c.target} personnes`;
 const caption=`<b>${esc(c.title)}</b>\n\n${esc(c.description)}\n\n<b>Accès :</b> ${type}`;
 const kb=Markup.inlineKeyboard([[Markup.button.url('🔓 Obtenir l’accès',`https://t.me/${(await bot.telegram.getMe()).username}?start=c_${c.id}`)]]);
 let msg;
 if(c.media_file_id&&c.media_type==='photo')msg=await bot.telegram.sendPhoto(config.MAIN_GROUP_ID,c.media_file_id,{caption,parse_mode:'HTML',...kb});
 else if(c.media_file_id&&c.media_type==='video')msg=await bot.telegram.sendVideo(config.MAIN_GROUP_ID,c.media_file_id,{caption,parse_mode:'HTML',...kb});
 else msg=await bot.telegram.sendMessage(config.MAIN_GROUP_ID,caption,{parse_mode:'HTML',...kb});
 await db.query(`UPDATE campaigns SET status='published',message_id=$2,published_at=now() WHERE id=$1`,[c.id,msg.message_id]);
}
async function sendContent(chatId:number,body:string,fileId?:string|null,mediaType?:string|null){
 if(fileId&&mediaType==='photo')return bot.telegram.sendPhoto(chatId,fileId,{caption:body});
 if(fileId&&mediaType==='video')return bot.telegram.sendVideo(chatId,fileId,{caption:body});
 return bot.telegram.sendMessage(chatId,body);
}
async function runBroadcast(target:'group'|'users',body:string,fileId?:string|null,mediaType?:string|null){
 if(target==='group'){await sendContent(config.MAIN_GROUP_ID,body,fileId,mediaType);return {sent:1,failed:0}}
 const users=await many<{telegram_id:string}>('SELECT telegram_id FROM users ORDER BY telegram_id');let sent=0,failed=0;
 for(const u of users){try{await sendContent(Number(u.telegram_id),body,fileId,mediaType);sent++}catch{failed++}await new Promise(r=>setTimeout(r,40))}
 return {sent,failed};
}
async function openCampaign(ctx:Context,id:number){
 if(!await privateOnly(ctx)||!ctx.from)return; const c=await one<Campaign>(`SELECT * FROM campaigns WHERE id=$1 AND status='published'`,[id]);
 if(!c)return void await ctx.reply('Cette publication n’est plus disponible.',back);
 const got=await one<{delivered_url:string|null}>(`SELECT delivered_url FROM entitlements WHERE user_id=$1 AND campaign_id=$2`,[ctx.from.id,id]); if(got)return void await ctx.reply(`✅ Ton accès :\n${got.delivered_url??c.gofile_url}`,back);
 if(c.access_type==='free'){
   const u=await one<{free_claims:number,invite_total:number}>(`SELECT free_claims,invite_total FROM users WHERE telegram_id=$1`,[ctx.from.id]);
   if((u?.free_claims??0)>0&&(u?.invite_total??0)===0)return void await ctx.reply('Pour obtenir un autre contenu gratuit, tu dois d’abord avoir au moins une invitation validée.',back);
   const granted=await db.query(`WITH added AS (INSERT INTO entitlements(user_id,campaign_id,delivered_url,release_version,delivered_at,guarantee_until) SELECT $1,id,gofile_url,release_version,now(),now()+($3||' hours')::interval FROM campaigns WHERE id=$2 ON CONFLICT DO NOTHING RETURNING 1) UPDATE users SET free_claims=free_claims+1 WHERE telegram_id=$1 AND EXISTS(SELECT 1 FROM added) RETURNING telegram_id`,[ctx.from.id,id,config.REISSUE_GUARANTEE_HOURS]);
   if(!granted.rowCount)return void await ctx.reply(`✅ Ton accès :\n${c.gofile_url}`,back);
   return void await ctx.reply(`✅ Accès débloqué :\n${c.gofile_url}`,back);
 }
 if(c.access_type==='paid'){
   const buttons: any[][]=[]; if(config.PAYPAL_URL)buttons.push([Markup.button.url('💳 PayPal',config.PAYPAL_URL)]);if(config.REVOLUT_URL)buttons.push([Markup.button.url('💳 Revolut',config.REVOLUT_URL)]);buttons.push([Markup.button.callback('📤 J’ai payé','paid_'+id)],[Markup.button.callback('⬅️ Retour','home')]);
   return void await ctx.reply(`<b>${esc(c.price_text??'Offre payante')}</b>\n\n${esc(config.PAYMENT_TEXT)}`,{parse_mode:'HTML',...Markup.inlineKeyboard(buttons)});
 }
 const active=await one<{active_campaign_id:number|null,invite_balance:number}>(`SELECT active_campaign_id,invite_balance FROM users WHERE telegram_id=$1`,[ctx.from.id]);
 if(active?.active_campaign_id&&active.active_campaign_id!==id)return void await ctx.reply('Tu as déjà un objectif actif. Tu peux y renoncer depuis « Ma progression » avant de commencer celui-ci.',back);
 await db.query(`UPDATE users SET active_campaign_id=$2 WHERE telegram_id=$1`,[ctx.from.id,id]); await tryUnlock(ctx.from.id);
 const link=await getOrCreateLink(ctx.from.id); const now=await one<{invite_balance:number}>(`SELECT invite_balance FROM users WHERE telegram_id=$1`,[ctx.from.id]);
 await ctx.reply(`🎯 Objectif : ${c.target}\nProgression disponible : ${now?.invite_balance??0}/${c.target}\n\nTon lien unique :\n${link}`,back);
}
async function tryUnlock(userId:number){
 const client=await db.connect();let unlocked:Campaign|null=null;
 try{await client.query('BEGIN');const u=(await client.query<{active_campaign_id:number|null,invite_balance:number}>(`SELECT active_campaign_id,invite_balance FROM users WHERE telegram_id=$1 FOR UPDATE`,[userId])).rows[0];if(!u?.active_campaign_id){await client.query('ROLLBACK');return}const c=(await client.query<Campaign>(`SELECT * FROM campaigns WHERE id=$1 AND status='published'`,[u.active_campaign_id])).rows[0];if(!c?.target||u.invite_balance<c.target){await client.query('ROLLBACK');return}const added=await client.query(`INSERT INTO entitlements(user_id,campaign_id,delivered_url,release_version,delivered_at,guarantee_until) VALUES($1,$2,$3,$4,now(),now()+($5||' hours')::interval) ON CONFLICT DO NOTHING RETURNING id`,[userId,c.id,c.gofile_url,c.release_version,config.REISSUE_GUARANTEE_HOURS]);if(!added.rowCount){await client.query(`UPDATE users SET active_campaign_id=NULL WHERE telegram_id=$1`,[userId]);await client.query('COMMIT');return}await client.query(`UPDATE users SET invite_balance=invite_balance-$2,active_campaign_id=NULL WHERE telegram_id=$1`,[userId,c.target]);await client.query('COMMIT');unlocked=c}catch(e){await client.query('ROLLBACK');throw e}finally{client.release()}
 if(unlocked)await bot.telegram.sendMessage(userId,`🎉 Objectif atteint !\n\n${unlocked.title}\n${unlocked.gofile_url}`).catch(()=>{});
}

bot.start(async ctx=>{await ensureUser(ctx);const p=ctx.payload;if(p?.startsWith('c_'))return openCampaign(ctx,Number(p.slice(2)));await showHome(ctx)});
bot.action('home',async ctx=>{await ctx.answerCbQuery();await showHome(ctx)});
bot.action('access',async ctx=>{await ctx.answerCbQuery();const rows=await many<{id:number,title:string,delivered_url:string}>(`SELECT c.id,c.title,COALESCE(e.delivered_url,c.gofile_url) delivered_url FROM entitlements e JOIN campaigns c ON c.id=e.campaign_id WHERE e.user_id=$1 ORDER BY e.granted_at DESC`,[ctx.from.id]);if(!rows.length)return void await ctx.editMessageText('Aucun accès débloqué.',back);const buttons=rows.flatMap(x=>[[Markup.button.url(`📂 ${x.title}`,x.delivered_url)],[Markup.button.callback(`⚠️ Lien expiré · ${x.title}`,`expired_${x.id}`)]]);buttons.push([Markup.button.callback('⬅️ Retour','home')]);await ctx.editMessageText('<b>Mes accès</b>\n\nOuvre un contenu ou signale un lien devenu inaccessible.',{parse_mode:'HTML',...Markup.inlineKeyboard(buttons)})});
bot.action(/^expired_(\d+)$/,async ctx=>{await ctx.answerCbQuery();const campaignId=Number(ctx.match[1]);const e=await one<{release_version:number,guarantee_until:Date|null}>(`SELECT release_version,guarantee_until FROM entitlements WHERE user_id=$1 AND campaign_id=$2`,[ctx.from.id,campaignId]);if(!e)return void await ctx.reply('Accès introuvable.',back);if(!e.guarantee_until||new Date(e.guarantee_until)<new Date())return void await ctx.reply(`La garantie de ${config.REISSUE_GUARANTEE_HOURS} heures est terminée. Utilise le signalement si tu rencontres un problème exceptionnel.`,back);const added=await db.query(`INSERT INTO reissue_requests(user_id,campaign_id,release_version) VALUES($1,$2,$3) ON CONFLICT DO NOTHING RETURNING id`,[ctx.from.id,campaignId,e.release_version]);if(!added.rowCount)return void await ctx.reply('Ta demande est déjà enregistrée. Tu recevras automatiquement le nouveau lien.',back);for(const id of config.ADMIN_IDS)await bot.telegram.sendMessage(id,`♻️ Nouvelle demande de rediffusion\nUtilisateur : ${ctx.from.id}\nPublication : #${campaignId}`).catch(()=>{});await ctx.reply('✅ Demande enregistrée. Le nouveau lien te sera envoyé automatiquement après son remplacement.',back)});
bot.action('invites',async ctx=>{await ctx.answerCbQuery();const link=await getOrCreateLink(ctx.from.id);await ctx.editMessageText(`Invite tes contacts avec ton lien personnel. Une invitation est validée après ${config.VALIDATION_MINUTES} minutes de présence.\n\n${link}`,back)});
bot.action('progress',async ctx=>{await ctx.answerCbQuery();const u=await one<{invite_balance:number,invite_total:number,active_campaign_id:number|null}>(`SELECT invite_balance,invite_total,active_campaign_id FROM users WHERE telegram_id=$1`,[ctx.from.id]);let text=`📊 Total validé : ${u?.invite_total??0}\nSolde disponible : ${u?.invite_balance??0}`;const rows=[[Markup.button.callback('⬅️ Retour','home')]];if(u?.active_campaign_id){const c=await one<Campaign>('SELECT * FROM campaigns WHERE id=$1',[u.active_campaign_id]);text+=`\n\nObjectif actif : ${c?.title}\n${u.invite_balance}/${c?.target}`;rows.unshift([Markup.button.callback('🏳️ Renoncer à cet objectif','quit_goal')])}await ctx.editMessageText(text,Markup.inlineKeyboard(rows))});
bot.action('quit_goal',async ctx=>{await ctx.answerCbQuery();await db.query(`UPDATE users SET active_campaign_id=NULL WHERE telegram_id=$1`,[ctx.from.id]);await ctx.editMessageText('Objectif abandonné. Ton solde d’invitations est conservé.',back)});
bot.action('notifications',async ctx=>{await ctx.answerCbQuery();const u=await one<{notifications:boolean}>(`UPDATE users SET notifications=NOT notifications WHERE telegram_id=$1 RETURNING notifications`,[ctx.from.id]);await ctx.editMessageText(`Notifications ${u?.notifications?'activées ✅':'désactivées 🔕'}.`,back)});
bot.action('report',async ctx=>{await ctx.answerCbQuery();const u=await one<{invite_total:number}>(`SELECT invite_total FROM users WHERE telegram_id=$1`,[ctx.from.id]);if(!u?.invite_total)return void await ctx.editMessageText('Le signalement est disponible après au moins une invitation validée.',back);await db.query(`INSERT INTO sessions(user_id,flow,step) VALUES($1,'report','kind') ON CONFLICT(user_id) DO UPDATE SET flow='report',step='kind',data='{}'`,[ctx.from.id]);await ctx.editMessageText('Que veux-tu signaler ?',Markup.inlineKeyboard([[Markup.button.callback('🐛 Bug','report_bug'),Markup.button.callback('⚠️ Problème','report_problem')],[Markup.button.callback('⬅️ Retour','home')]]))});
bot.action(/^report_(bug|problem)$/,async ctx=>{await ctx.answerCbQuery();await db.query(`UPDATE sessions SET step='body',data=jsonb_build_object('kind',$2) WHERE user_id=$1`,[ctx.from.id,ctx.match[1]]);await ctx.editMessageText('Décris précisément la situation dans ton prochain message.',back)});

bot.action('admin',async ctx=>{await ctx.answerCbQuery();if(!isAdmin(ctx.from.id))return;await ctx.editMessageText('🛠 <b>Administration</b>',{parse_mode:'HTML',...adminKb})});
bot.action('broadcast',async ctx=>{await ctx.answerCbQuery();if(!isAdmin(ctx.from.id))return;await ctx.editMessageText('Où veux-tu envoyer le broadcast ?',Markup.inlineKeyboard([[Markup.button.callback('👥 Groupe principal','broadcast_group')],[Markup.button.callback('📨 Tous les utilisateurs privés','broadcast_users')],[Markup.button.callback('⬅️ Administration','admin')]]))});
bot.action(/^broadcast_(group|users)$/,async ctx=>{await ctx.answerCbQuery();if(!isAdmin(ctx.from.id))return;await db.query(`INSERT INTO sessions(user_id,flow,step,data) VALUES($1,'broadcast','content',jsonb_build_object('target',$2)) ON CONFLICT(user_id) DO UPDATE SET flow='broadcast',step='content',data=jsonb_build_object('target',$2),updated_at=now()`,[ctx.from.id,ctx.match[1]]);await ctx.editMessageText('Envoie maintenant le texte, la photo ou la vidéo à diffuser. Pour un média, sa légende sera utilisée comme texte.',back)});
bot.action('ads',async ctx=>{await ctx.answerCbQuery();if(!isAdmin(ctx.from.id))return;const ads=await many<Ad>('SELECT * FROM scheduled_ads ORDER BY id');const rows=ads.map(a=>[Markup.button.callback(`${a.enabled?'🟢':'⚪️'} #${a.id} ${a.name}`,`ad_toggle_${a.id}`)]);rows.push([Markup.button.callback('➕ Nouvelle pub','ad_new')],[Markup.button.callback('▶️ Publier maintenant','ad_run')],[Markup.button.callback('⬅️ Administration','admin')]);await ctx.editMessageText(`⏱ <b>Rotation toutes les 6 heures</b>\n\n${ads.length?'Appuie sur une pub pour l’activer ou la désactiver.':'Aucune publicité configurée.'}`,{parse_mode:'HTML',...Markup.inlineKeyboard(rows)})});
bot.action('ad_new',async ctx=>{await ctx.answerCbQuery();if(!isAdmin(ctx.from.id))return;await db.query(`INSERT INTO sessions(user_id,flow,step,data) VALUES($1,'ad','name','{}') ON CONFLICT(user_id) DO UPDATE SET flow='ad',step='name',data='{}',updated_at=now()`,[ctx.from.id]);await ctx.editMessageText('Envoie un nom interne pour reconnaître cette publicité.',back)});
bot.action(/^ad_toggle_(\d+)$/,async ctx=>{await ctx.answerCbQuery();if(!isAdmin(ctx.from.id))return;await db.query('UPDATE scheduled_ads SET enabled=NOT enabled WHERE id=$1',[Number(ctx.match[1])]);await ctx.reply('État de la publicité modifié.',adminKb)});
bot.action('ad_run',async ctx=>{await ctx.answerCbQuery('Publication en cours…');if(!isAdmin(ctx.from.id))return;const done=await publishNextAd(true);await ctx.reply(done?'✅ Nouvelle pub publiée, précédente supprimée.':'Aucune publicité active.',adminKb)});
bot.action('reissues',async ctx=>{await ctx.answerCbQuery();if(!isAdmin(ctx.from.id))return;const rows=await many<{id:number,title:string,pending:string}>(`SELECT c.id,c.title,count(r.id) FILTER(WHERE r.status='pending')::text pending FROM campaigns c LEFT JOIN reissue_requests r ON r.campaign_id=c.id GROUP BY c.id,c.title ORDER BY c.id DESC LIMIT 10`);if(!rows.length)return void await ctx.editMessageText('Aucune publication disponible.',adminKb);const buttons=rows.flatMap(x=>[[Markup.button.callback(`♻️ ${x.title} · ${x.pending} attente(s)`,`reissue_pending_${x.id}`)],[Markup.button.callback(`📢 ${x.title} · renvoyer à tous`,`reissue_all_${x.id}`)]]);buttons.push([Markup.button.callback('⬅️ Administration','admin')]);await ctx.editMessageText('Choisis une publication puis envoie son nouveau lien. « Tous » est exceptionnel et concerne tous les bénéficiaires.',Markup.inlineKeyboard(buttons))});
bot.action(/^reissue_(pending|all)_(\d+)$/,async ctx=>{await ctx.answerCbQuery();if(!isAdmin(ctx.from.id))return;await db.query(`INSERT INTO sessions(user_id,flow,step,data) VALUES($1,'reissue','url',jsonb_build_object('mode',$2,'campaign_id',$3::int)) ON CONFLICT(user_id) DO UPDATE SET flow='reissue',step='url',data=jsonb_build_object('mode',$2,'campaign_id',$3::int),updated_at=now()`,[ctx.from.id,ctx.match[1],Number(ctx.match[2])]);await ctx.editMessageText('Envoie le nouveau lien GoFile. Il deviendra la nouvelle version active.',back)});
bot.action('new_campaign',async ctx=>{await ctx.answerCbQuery();if(!isAdmin(ctx.from.id))return;await db.query(`INSERT INTO sessions(user_id,flow,step) VALUES($1,'campaign','title') ON CONFLICT(user_id) DO UPDATE SET flow='campaign',step='title',data='{}'`,[ctx.from.id]);await ctx.editMessageText('Envoie le titre de la publication.',back)});
bot.action(/^ctype_(free|paid|invite)$/,async ctx=>{await ctx.answerCbQuery();if(!isAdmin(ctx.from.id))return;const type=ctx.match[1];await db.query(`UPDATE sessions SET data=data||jsonb_build_object('access_type',$2),step=$3 WHERE user_id=$1`,[ctx.from.id,type,type==='invite'?'target':type==='paid'?'price':'url']);await ctx.editMessageText(type==='invite'?'Envoie le nombre d’invitations requis.':type==='paid'?'Envoie le prix et les détails de l’offre.':'Envoie le lien GoFile.',back)});
bot.action(/^publish_(\d+)$/,async ctx=>{await ctx.answerCbQuery();if(!isAdmin(ctx.from.id))return;const c=await one<Campaign>('SELECT * FROM campaigns WHERE id=$1',[Number(ctx.match[1])]);if(c){await publish(c);await ctx.editMessageText('✅ Publication envoyée dans le groupe.',adminKb)}});
bot.action(/^paid_(\d+)$/,async ctx=>{await ctx.answerCbQuery('Demande envoyée');const c=await one<Campaign>('SELECT * FROM campaigns WHERE id=$1',[Number(ctx.match[1])]);for(const id of config.ADMIN_IDS)await bot.telegram.sendMessage(id,`💳 Paiement déclaré\nUtilisateur : ${ctx.from.id} @${ctx.from.username??'-'}\nOffre : ${c?.title}`,Markup.inlineKeyboard([[Markup.button.callback('✅ Valider',`grant_${ctx.from.id}_${c?.id}`)],[Markup.button.callback('❌ Refuser',`deny_${ctx.from.id}_${c?.id}`)]])).catch(()=>{});await ctx.editMessageText('Ta demande a été transmise. Tu recevras une réponse après vérification.',back)});
bot.action(/^grant_(\d+)_(\d+)$/,async ctx=>{await ctx.answerCbQuery();if(!isAdmin(ctx.from.id))return;const uid=Number(ctx.match[1]),cid=Number(ctx.match[2]);const c=await one<Campaign>('SELECT * FROM campaigns WHERE id=$1',[cid]);if(!c)return;await db.query(`INSERT INTO entitlements(user_id,campaign_id,delivered_url,release_version,delivered_at,guarantee_until) VALUES($1,$2,$3,$4,now(),now()+($5||' hours')::interval) ON CONFLICT DO NOTHING`,[uid,cid,c.gofile_url,c.release_version,config.REISSUE_GUARANTEE_HOURS]);await bot.telegram.sendMessage(uid,`✅ Paiement validé.\n${c.gofile_url}`).catch(()=>{});await ctx.editMessageText('Paiement validé.')});
bot.action(/^deny_(\d+)_(\d+)$/,async ctx=>{await ctx.answerCbQuery();if(!isAdmin(ctx.from.id))return;await bot.telegram.sendMessage(Number(ctx.match[1]),'❌ Le paiement n’a pas pu être validé. Contacte un administrateur.').catch(()=>{});await ctx.editMessageText('Paiement refusé.')});
bot.action('words',async ctx=>{await ctx.answerCbQuery();if(!isAdmin(ctx.from.id))return;const w=await many<{word:string}>('SELECT word FROM banned_words ORDER BY word');await ctx.editMessageText(`🚫 Mots interdits : ${w.map(x=>x.word).join(', ')||'aucun'}\n\nEnvoie : <code>+ mot</code> ou <code>- mot</code>`,{parse_mode:'HTML',...adminKb})});
bot.action('campaigns',async ctx=>{await ctx.answerCbQuery();if(!isAdmin(ctx.from.id))return;const cs=await many<Campaign>('SELECT * FROM campaigns ORDER BY id DESC LIMIT 20');await ctx.editMessageText(cs.length?cs.map(c=>`#${c.id} ${c.title} — ${c.status}`).join('\n'):'Aucune publication.',adminKb)});
bot.action('reports',async ctx=>{await ctx.answerCbQuery();if(!isAdmin(ctx.from.id))return;const rs=await many<{id:number,user_id:string,kind:string,body:string}>(`SELECT * FROM reports WHERE status='open' ORDER BY id DESC LIMIT 20`);await ctx.editMessageText(rs.length?rs.map(r=>`#${r.id} · ${r.kind} · ${r.user_id}\n${r.body}`).join('\n\n'):'Aucun signalement ouvert.',adminKb)});

bot.on('text',async ctx=>{
 await ensureUser(ctx);if(ctx.chat.type!=='private')return;
 if(isAdmin(ctx.from.id)&&/^[+-]\s+\S+/.test(ctx.message.text)){const [op,...parts]=ctx.message.text.trim().split(/\s+/);const word=parts.join(' ').toLocaleLowerCase('fr-FR');if(op==='+')await db.query('INSERT INTO banned_words(word) VALUES($1) ON CONFLICT DO NOTHING',[word]);else await db.query('DELETE FROM banned_words WHERE word=$1',[word]);return void await ctx.reply(`Mot « ${word} » ${op==='+'?'ajouté':'retiré'}.`,adminKb)}
 const s=await one<{flow:string,step:string,data:any}>('SELECT * FROM sessions WHERE user_id=$1',[ctx.from.id]);if(!s)return;
 const text=ctx.message.text.trim();
 if(s.flow==='reissue'&&s.step==='url'&&isAdmin(ctx.from.id)){
  if(!/^https?:\/\//.test(text))return void await ctx.reply('Le lien doit commencer par http:// ou https://');const cid=Number(s.data.campaign_id),mode=s.data.mode as 'pending'|'all';const c=await one<Campaign>(`UPDATE campaigns SET gofile_url=$2,release_version=release_version+1 WHERE id=$1 RETURNING *`,[cid,text]);if(!c)return void await ctx.reply('Publication introuvable.',adminKb);const recipients=mode==='all'?await many<{user_id:string}>(`SELECT user_id::text FROM entitlements WHERE campaign_id=$1`,[cid]):await many<{user_id:string}>(`SELECT DISTINCT user_id::text FROM reissue_requests WHERE campaign_id=$1 AND status='pending'`,[cid]);let sent=0,failed=0;for(const r of recipients){const uid=Number(r.user_id);try{await bot.telegram.sendMessage(uid,`♻️ Nouveau lien disponible pour « ${c.title} » :\n${text}`);await db.query(`UPDATE entitlements SET delivered_url=$3,release_version=$4,delivered_at=now(),guarantee_until=now()+($5||' hours')::interval WHERE user_id=$1 AND campaign_id=$2`,[uid,cid,text,c.release_version,config.REISSUE_GUARANTEE_HOURS]);await db.query(`UPDATE reissue_requests SET status='fulfilled',fulfilled_at=now() WHERE user_id=$1 AND campaign_id=$2 AND status='pending'`,[uid,cid]);sent++}catch{failed++}await new Promise(r=>setTimeout(r,40))}await db.query('DELETE FROM sessions WHERE user_id=$1',[ctx.from.id]);return void await ctx.reply(`✅ Nouvelle version enregistrée.\nEnvoyés : ${sent}\nÉchecs : ${failed}`,adminKb)
 }
 if(s.flow==='broadcast'&&s.step==='content'&&isAdmin(ctx.from.id)){const result=await runBroadcast(s.data.target,text);await db.query('DELETE FROM sessions WHERE user_id=$1',[ctx.from.id]);return void await ctx.reply(`✅ Broadcast terminé.\nEnvoyés : ${result.sent}\nÉchecs : ${result.failed}`,adminKb)}
 if(s.flow==='ad'&&isAdmin(ctx.from.id)){
  if(s.step==='name'){await db.query(`UPDATE sessions SET step='body',data=jsonb_build_object('name',$2) WHERE user_id=$1`,[ctx.from.id,text]);return void await ctx.reply('Envoie le texte de la publicité.')}
  if(s.step==='body'){await db.query(`UPDATE sessions SET step='media',data=data||jsonb_build_object('body',$2) WHERE user_id=$1`,[ctx.from.id,text]);return void await ctx.reply('Envoie une photo/vidéo, ou écris « passer » pour une pub texte.')}
  if(s.step==='media'&&text.toLowerCase()==='passer'){await db.query(`INSERT INTO scheduled_ads(name,body,created_by) VALUES($1,$2,$3)`,[s.data.name,s.data.body,ctx.from.id]);await db.query('DELETE FROM sessions WHERE user_id=$1',[ctx.from.id]);return void await ctx.reply('✅ Publicité ajoutée et activée dans la rotation.',adminKb)}
 }
 if(s.flow==='report'&&s.step==='body'){await db.query(`INSERT INTO reports(user_id,kind,body) VALUES($1,$2,$3)`,[ctx.from.id,s.data.kind,text]);await db.query('DELETE FROM sessions WHERE user_id=$1',[ctx.from.id]);for(const id of config.ADMIN_IDS)await bot.telegram.sendMessage(id,`🛟 Nouveau signalement de ${ctx.from.id}\n${text}`).catch(()=>{});return void await ctx.reply('Merci, ton signalement a été transmis.',home(isAdmin(ctx.from.id)))}
 if(s.flow!=='campaign'||!isAdmin(ctx.from.id))return;
 if(s.step==='title'){await db.query(`UPDATE sessions SET step='description',data=jsonb_build_object('title',$2) WHERE user_id=$1`,[ctx.from.id,text]);return void await ctx.reply('Envoie maintenant la description.')}
 if(s.step==='description'){await db.query(`UPDATE sessions SET step='media',data=data||jsonb_build_object('description',$2) WHERE user_id=$1`,[ctx.from.id,text]);return void await ctx.reply('Envoie une photo/vidéo, ou écris « passer ».')}
 if(s.step==='media'&&text.toLowerCase()==='passer'){await db.query(`UPDATE sessions SET step='type' WHERE user_id=$1`,[ctx.from.id]);return void await ctx.reply('Choisis le type d’accès.',Markup.inlineKeyboard([[Markup.button.callback('🆓 Gratuit','ctype_free'),Markup.button.callback('💳 Payant','ctype_paid')],[Markup.button.callback('🎯 Invitation','ctype_invite')]]))}
 if(s.step==='target'){const n=Number(text);if(!Number.isInteger(n)||n<1)return void await ctx.reply('Envoie un nombre entier supérieur à 0.');await db.query(`UPDATE sessions SET step='url',data=data||jsonb_build_object('target',$2) WHERE user_id=$1`,[ctx.from.id,n]);return void await ctx.reply('Envoie le lien GoFile.')}
 if(s.step==='price'){await db.query(`UPDATE sessions SET step='url',data=data||jsonb_build_object('price_text',$2) WHERE user_id=$1`,[ctx.from.id,text]);return void await ctx.reply('Envoie le lien GoFile.')}
 if(s.step==='url'){if(!/^https?:\/\//.test(text))return void await ctx.reply('Le lien doit commencer par http:// ou https://');const d=s.data;const r=await db.query(`INSERT INTO campaigns(title,description,media_file_id,media_type,access_type,target,gofile_url,price_text,created_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9) RETURNING id`,[d.title,d.description,d.media_file_id??null,d.media_type??null,d.access_type,d.target??null,text,d.price_text??null,ctx.from.id]);await db.query('DELETE FROM sessions WHERE user_id=$1',[ctx.from.id]);return void await ctx.reply('Vérifie puis publie.',Markup.inlineKeyboard([[Markup.button.callback('🚀 Publier',`publish_${r.rows[0].id}`)],[Markup.button.callback('⬅️ Administration','admin')]]))}
});
bot.on(['photo','video'],async ctx=>{if(ctx.chat.type!=='private'||!isAdmin(ctx.from.id))return;const s=await one<{flow:string,step:string,data:any}>('SELECT flow,step,data FROM sessions WHERE user_id=$1',[ctx.from.id]);const photo='photo' in ctx.message;const id=photo?ctx.message.photo.at(-1)!.file_id:ctx.message.video.file_id;const mediaType=photo?'photo':'video';const caption=ctx.message.caption?.trim()??'';
 if(s?.flow==='broadcast'&&s.step==='content'){const body=caption||' ';const result=await runBroadcast(s.data.target,body,id,mediaType);await db.query('DELETE FROM sessions WHERE user_id=$1',[ctx.from.id]);return void await ctx.reply(`✅ Broadcast terminé.\nEnvoyés : ${result.sent}\nÉchecs : ${result.failed}`,adminKb)}
 if(s?.flow==='ad'&&s.step==='media'){await db.query(`INSERT INTO scheduled_ads(name,body,media_file_id,media_type,created_by) VALUES($1,$2,$3,$4,$5)`,[s.data.name,s.data.body,id,mediaType,ctx.from.id]);await db.query('DELETE FROM sessions WHERE user_id=$1',[ctx.from.id]);return void await ctx.reply('✅ Publicité avec média ajoutée et activée.',adminKb)}
 if(s?.flow!=='campaign'||s.step!=='media')return;await db.query(`UPDATE sessions SET step='type',data=data||jsonb_build_object('media_file_id',$2,'media_type',$3) WHERE user_id=$1`,[ctx.from.id,id,mediaType]);await ctx.reply('Média enregistré. Choisis le type d’accès.',Markup.inlineKeyboard([[Markup.button.callback('🆓 Gratuit','ctype_free'),Markup.button.callback('💳 Payant','ctype_paid')],[Markup.button.callback('🎯 Invitation','ctype_invite')]]))});

bot.on('chat_member',async ctx=>{
 if(ctx.chat.id!==config.MAIN_GROUP_ID)return;const u=ctx.chatMember.new_chat_member.user;const old=ctx.chatMember.old_chat_member.status,newS=ctx.chatMember.new_chat_member.status;
 if(['left','kicked'].includes(old)&&['member','restricted'].includes(newS)){
  const words=await many<{word:string}>('SELECT word FROM banned_words');const name=[u.first_name,u.last_name,u.username].filter(Boolean).join(' ').toLocaleLowerCase('fr-FR');const tokens: string[]=name.match(/[\p{L}\p{N}_]+/gu)??[];if(words.some(w=>tokens.includes(w.word.toLocaleLowerCase('fr-FR')))){await bot.telegram.banChatMember(config.MAIN_GROUP_ID,u.id);return}
  const link=ctx.chatMember.invite_link?.invite_link;if(link){const owner=await one<{owner_id:string}>('SELECT owner_id FROM invite_links WHERE invite_link=$1 AND revoked_at IS NULL',[link]);if(owner&&Number(owner.owner_id)!==u.id){await ensureUser(ctx);await db.query(`INSERT INTO invite_joins(invitee_id,inviter_id,invite_link,validate_at) VALUES($1,$2,$3,now()+($4||' minutes')::interval) ON CONFLICT(invitee_id) DO NOTHING`,[u.id,owner.owner_id,link,config.VALIDATION_MINUTES])}}
 } else if(['member','restricted'].includes(old)&&['left','kicked'].includes(newS))await db.query(`UPDATE invite_joins SET status='left' WHERE invitee_id=$1 AND status='pending'`,[u.id]);
});
bot.on('message',async ctx=>{
 if(ctx.chat.id!==config.MAIN_GROUP_ID)return;if('new_chat_members'in ctx.message||'left_chat_member'in ctx.message){await ctx.deleteMessage().catch(()=>{});return}
 if(!isAdmin(ctx.from?.id))await ctx.deleteMessage().catch(()=>{});
});
bot.on('my_chat_member',async ctx=>{if(['member','administrator'].includes(ctx.myChatMember.new_chat_member.status)&&ctx.chat.id!==config.MAIN_GROUP_ID)await bot.telegram.leaveChat(ctx.chat.id).catch(()=>{})});

async function validatePending(){const rows=await many<{id:number,invitee_id:string,inviter_id:string}>(`SELECT id,invitee_id,inviter_id FROM invite_joins WHERE status='pending' AND validate_at<=now() LIMIT 100`);for(const r of rows){try{const m=await bot.telegram.getChatMember(config.MAIN_GROUP_ID,Number(r.invitee_id));if(!['member','administrator','creator','restricted'].includes(m.status)){await db.query(`UPDATE invite_joins SET status='left' WHERE id=$1`,[r.id]);continue}const q=await db.query(`UPDATE invite_joins SET status='counted' WHERE id=$1 AND status='pending' RETURNING id`,[r.id]);if(!q.rowCount)continue;await db.query(`UPDATE users SET invite_balance=invite_balance+1,invite_total=invite_total+1 WHERE telegram_id=$1`,[r.inviter_id]);await tryUnlock(Number(r.inviter_id));const u=await one<{notifications:boolean,invite_balance:number}>(`SELECT notifications,invite_balance FROM users WHERE telegram_id=$1`,[r.inviter_id]);if(u?.notifications)await bot.telegram.sendMessage(Number(r.inviter_id),`✅ Une invitation vient d’être validée.\nSolde disponible : ${u.invite_balance}`).catch(()=>{})}catch(e){console.error('validation',e)}}}
async function publishNextAd(force=false){
 const client=await db.connect();let ad:Ad|undefined;let previousMessageId:number|null=null;
 try{await client.query('BEGIN');await client.query(`SELECT pg_advisory_xact_lock(731946)`);const setting=(await client.query<{value:{next_at:string|null,last_message_id:number|null,last_ad_id:number|null}}>(`SELECT value FROM app_settings WHERE key='ad_rotation' FOR UPDATE`)).rows[0];const state=setting?.value??{next_at:null,last_message_id:null,last_ad_id:null};if(!force&&state.next_at&&new Date(state.next_at)>new Date()){await client.query('ROLLBACK');return false}const picked=await client.query<Ad>(`SELECT * FROM scheduled_ads WHERE enabled=TRUE ORDER BY CASE WHEN id>$1 THEN 0 ELSE 1 END,id LIMIT 1`,[state.last_ad_id??0]);ad=picked.rows[0];if(!ad){await client.query('ROLLBACK');return false}previousMessageId=state.last_message_id;await client.query(`UPDATE app_settings SET value=jsonb_build_object('next_at',now()+interval '6 hours','last_message_id',NULL,'last_ad_id',$2),updated_at=now() WHERE key='ad_rotation'`,[null,ad.id]);await client.query('COMMIT')}catch(e){await client.query('ROLLBACK');throw e}finally{client.release()}
 if(previousMessageId)await bot.telegram.deleteMessage(config.MAIN_GROUP_ID,previousMessageId).catch(()=>{});const sent=await sendContent(config.MAIN_GROUP_ID,ad.body,ad.media_file_id,ad.media_type);await db.query(`UPDATE scheduled_ads SET last_sent_at=now() WHERE id=$1`,[ad.id]);await db.query(`UPDATE app_settings SET value=jsonb_set(value,'{last_message_id}',to_jsonb($1::bigint)),updated_at=now() WHERE key='ad_rotation'`,[sent.message_id]);return true;
}
async function startup(){const me=await bot.telegram.getMe();const member=await bot.telegram.getChatMember(config.MAIN_GROUP_ID,me.id);if(member.status!=='administrator')throw new Error('Le bot doit être administrateur du groupe principal.');await bot.telegram.setChatPermissions(config.MAIN_GROUP_ID,{can_send_messages:false,can_send_audios:false,can_send_documents:false,can_send_photos:false,can_send_videos:false,can_send_video_notes:false,can_send_voice_notes:false,can_send_polls:false,can_send_other_messages:false,can_add_web_page_previews:false,can_change_info:false,can_invite_users:false,can_pin_messages:false,can_manage_topics:false});await bot.launch({allowedUpdates:['message','callback_query','chat_member','my_chat_member']});setInterval(validatePending,30_000);setInterval(()=>publishNextAd().catch(e=>console.error('ad rotation',e)),60_000);await publishNextAd().catch(e=>console.error('ad startup',e));console.log(`@${me.username} started`)}
process.once('SIGINT',()=>bot.stop('SIGINT'));process.once('SIGTERM',()=>bot.stop('SIGTERM'));startup().catch(e=>{console.error(e);process.exit(1)});
